src/BigPandaDev/MainBundle/Entity/Users.php
<?php
namespace BigPandaDev\MainBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Symfony\Component\HttpFoundation\Session\Session;

/**
 * @ORM\Table(name="app_users")
 * @ORM\Entity(repositoryClass="BigPandaDev\MainBundle\EntityRepository\UsersRepository")
 */
class Users implements AdvancedUserInterface, \Serializable
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=25, unique=true)
     */
    private $username;
    
    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;
    
    /**
     * @ORM\Column(type="string", length=60, unique=true)
     */
    private $email;
    
    /**
     * @ORM\ManyToOne(targetEntity="UserRoles")
     * @ORM\JoinColumn(name="role_id", referencedColumnName="id")
     */
    private $role;
    
    /**
     * @ORM\Column(name="deleted", type="boolean")
     */
    private $deleted = 0;
    
    /**
     * @ORM\Column(name="deleted_by", type="string", length=60, nullable=true)
     */
    private $deletedBy;
    
    
    

    public function __construct()
    {
        $this->deleted = 0;
        // may not be needed, see section on salt below
        // $this->salt = md5(uniqid(null, true));
    }

    public function getUsername()
    {
        return $this->username;
    }
    
    public function getRoles() {
        return array($this->getRole()->getName() );
    }
    
    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    public function getPassword()
    {
        return $this->password;
    }
    
    public function eraseCredentials()
    {
    }
    
    public function getLocale() {
        return null;
    }
    
    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return !$this->deleted;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt,
            !$this->deleted,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        $active = !$this->deleted;
        list (
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt
            $active,
        ) = unserialize($serialized);
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     *
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     *
     * @return User
     */
    public function setIsActive($isActive)
    {
        $this->deleted = !$isActive;

        return $this;
    }

    /**
     * Get isActive
     *
     * @return boolean
     */
    public function getIsActive()
    {
        return !$this->deleted;
    }

    /**
     * Set role
     *
     * @param \BigPandaDev\MainBundle\Entity\UserRole $role
     *
     * @return User
     */
    public function setRole(\BigPandaDev\MainBundle\Entity\UserRoles $role = null)
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Get role
     *
     * @return \BigPandaDev\MainBundle\Entity\UserRole
     */
    public function getRole()
    {
        return $this->role;
    }
    
    /**
     * Set deleted
     *
     * @return User
     */
    public function setName($username)
    {
        $this->username;
        return $this;
    }
    
    /**
     * Get deleted
     *
     * @return boolean
     */
    public function getName()
    {
        return $this->username;
    }

    /**
     * Set deleted
     *
     * @param boolean $deleted
     *
     * @return User
     */
    public function setDeleted($deleted)
    {
        $this->deleted = $deleted;

        return $this;
    }

    /**
     * Get deleted
     *
     * @return boolean
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /**
     * Set deletedBy
     *
     * @param string $deletedBy
     *
     * @return User
     */
    public function setDeletedBy($deletedBy)
    {
        $this->deletedBy = $deletedBy;

        return $this;
    }

    /**
     * Get deletedBy
     *
     * @return string
     */
    public function getDeletedBy()
    {
        return $this->deletedBy;
    }
}

src/BigPandaDev/MainBundle/Resources/views/Navs/breadcrumb.html.twig
{% macro breadcrumb(name) %}
    {% set breadcrumb_nav_list = [
        {'name':'home',         'label':'Home',             'href':path('_home')},

        {'name':'offers',       'parent':'home',        'label':'Offers', 'href':path('_offers')},
        {'name':'offer',        'parent':'offers',      'label':'Offer details', 'href':'#'},

        {'name':'orders',       'parent':'home',        'label':'Orders', 'href':path('_orders')},
        {'name':'order',        'parent':'orders',      'label':'Order details', 'href':'#'},

        {'name':'code_lists',   'parent':'home',        'label':'Code lists', 'href':'#'},

        {'name':'job_types',    'parent':'code_lists',  'label':'Job types', 'href':path('_job_types')},
        {'name':'job_type',     'parent':'job_types',   'label':'Job type details', 'href':'#'},

        {'name':'users',    'parent':'code_lists',  'label':'Users', 'href':path('_users')},
        {'name':'user',     'parent':'users',   'label':'User details', 'href':'#'}
    ] %}
    
    {% for item in breadcrumb_nav_list %}
        {% if item.name == name %}
            {% if item.parent is defined %}
                {{ _self.breadcrumb(item.parent) }} / 
            {% endif %}
            <a href="{{ item.href }}">{{ item.label|trans }}</a>
        {% endif %}
    {% endfor %}
{% endmacro %}

src/BigPandaDev/MainBundle/Resources/views/Navs/main.html.twig
{% set main_nav_name = 'main_nav_public' %}
{% if app.user and is_granted('ROLE_ADMIN') %}
    {% set main_nav_name = 'main_nav_admin' %}
{% elseif app.user and is_granted('ROLE_EMPLOYEE') %}
    {% set main_nav_name = 'main_nav_employee' %}
{% elseif app.user and is_granted('ROLE_CUSTOMER') %}
    {% set main_nav_name = 'main_nav_customer' %}
{% endif %}

<nav id="main-nav" class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ path('_homepage') }}">BigPanda</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topnav">
                <i class="fa fa-bars navicon"></i>
            </button>    
        </div>
        <div class="navbar-collapse collapse" id="topnav">
            {% include 'BigPandaDevMainBundle:Navs:' ~ main_nav_name ~ '.html.twig' %}
            
            <ul class="nav navbar-nav navbar-right">
                {% if app.user %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-male navicon"></i> <span>({{ app.user.username }})</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">{{ app.user.username }}</li>
                            <li><a href="{{ path('_home') }}"><i class="fa fa-male"></i> {{ 'Home'|trans }}</a></li>
                            <li><a href="#"><i class="fa fa-male"></i> {{ 'Profile'|trans }}</a></li>
                            <li><a href="{{ path('_logout') }}"><i class="fa fa-sign-out"></i> {{ 'Logout'|trans }}</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#"><i class="fa fa-cogs"></i> {{ 'Settings'|trans }}</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{{ path('_login') }}"><i class="fa fa-sign-in navicon"></i> {{ 'Login'|trans }}</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

src/BigPandaDev/MainBundle/Resources/views/Navs/main_nav_admin.html.twig
<ul class="nav navbar-nav navbar-left">
{#    <li><a href="{{ path('_home') }}"><i class="fa fa-home navicon"></i> <span>{{ 'Home'|trans }}</span></a></li>#}
    
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-circle-o navicon"></i> <span>{{ 'Blog'|trans }}</span> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="#blog/posts"><i class="fa fa-cog"></i> <span>{{ 'Posts'|trans }}</span></a></li>
            <li><a href="#blog/myposts{#{ path('_orders') }#}"><i class="fa fa-list-alt"></i> <span>{{ 'My posts'|trans }}</span></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#blog/stats"><i class="fa fa-circle-o"></i> <span>{{ 'Blog statistics'|trans }}</span></a></li>
        </ul>
    </li>
    
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-circle-o navicon"></i> <span>{{ 'My offers'|trans }}</span> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="{{ path('_offers') }}"><i class="fa fa-circle-o"></i> {{ 'Offers'|trans }}</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{{ path('_job_types') }}"><i class="fa fa-circle-o"></i> {{ 'Job types'|trans }}</a></li>
        </ul>
    </li>
    
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-circle-o navicon"></i> <span>{{ 'My jobs'|trans }}</span> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="{{ path('_orders') }}"><i class="fa fa-list-alt"></i> <span>{{ 'Orders'|trans }}</span></a></li>
            <li><a href="#tasks"><i class="fa fa-cog"></i> <span>{{ 'Tasks'|trans }}</span></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#paynaments"><i class="fa fa-cart-plus"></i> <span>{{ 'Payments'|trans }}</span></a></li>
            <li><a href="#feedbacks"><i class="fa fa-envelope"></i> <span>{{ 'Feedbacks'|trans }}</span></a></li>
        </ul>
    </li>
    
    <li><a href="#stats"><i class="fa fa-line-chart navicon"></i> <span>{{ 'Statistics'|trans }}</span></a></li>
    <li><a href="#admin"><i class="fa fa-lock navicon"></i> <span>{{ 'Admin panel'|trans }}</span></a></li>
    
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-circle-o navicon"></i> <span>{{ 'Code lists'|trans }}</span> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="{{ path('_job_types') }}"><i class="fa fa-circle-o"></i> {{ 'Job types'|trans }}</a></li>
            <li><a href="{{ path('_users') }}"><i class="fa fa-circle-o"></i> {{ 'Users'|trans }}</a></li>
        </ul>
    </li>
    
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-circle-o navicon"></i> <span>{{ 'Help'|trans }}</span> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="#"><i class="fa fa-question-circle"></i> <span>{{ 'About'|trans }}</span></a></li>
            <li><a href="#"><i class="fa fa-envelope-o"></i> <span>{{ 'Contact'|trans }}</span></a></li>
        </ul>
    </li>
    
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-globe navicon"></i> <span>{{ app.request.locale|upper }}</span> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            {% if app.request.locale != 'en' %}<li><a href="{{ path('_language_change', {'lang':'en'}) }}">EN</a></li>{% endif %}
            {% if app.request.locale != 'hr' %}<li><a href="{{ path('_language_change', {'lang':'hr'}) }}">HR</a></li>{% endif %}
        </ul>
    </li>
</ul>

src/BigPandaDev/MainBundle/Resources/views/Navs/main_nav_customer.html.twig
<ul class="nav navbar-nav navbar-left">
    <li><a href="{{ path('_home') }}"><i class="fa fa-home navicon"></i> <span>{{ 'Home'|trans }}</span></a></li>
    <li><a href="{{ path('_orders') }}"><i class="fa fa-list-alt navicon"></i> <span>{{ 'Orders'|trans }}</span></a></li>
    <li><a href="#paynaments"><i class="fa fa-cart-plus navicon"></i> <span>{{ 'Payments'|trans }}</span></a></li>
    <li><a href="#feedbacks"><i class="fa fa-envelope navicon"></i> <span>{{ 'Feedbacks'|trans }}</span></a></li>
    <li><a href="#stats"><i class="fa fa-line-chart navicon"></i> <span>{{ 'Statistics'|trans }}</span></a></li>
    
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-circle-o navicon"></i> <span>{{ 'Help'|trans }}</span> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="#"><i class="fa fa-question-circle"></i> <span>{{ 'About'|trans }}</span></a></li>
            <li><a href="#"><i class="fa fa-envelope-o"></i> <span>{{ 'Contact'|trans }}</span></a></li>
        </ul>
    </li>
    
    
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-globe navicon"></i> <span>{{ app.request.locale|upper }}</span> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            {% if app.request.locale != 'en' %}<li><a href="{{ path('_language_change', {'lang':'en'}) }}">EN</a></li>{% endif %}
            {% if app.request.locale != 'hr' %}<li><a href="{{ path('_language_change', {'lang':'hr'}) }}">HR</a></li>{% endif %}
        </ul>
    </li>
</ul>

src/BigPandaDev/MainBundle/Resources/views/Navs/main_nav_employee.html.twig
<ul class="nav navbar-nav navbar-left">
    <li><a href="{{ path('_home') }}"><i class="fa fa-home navicon"></i> <span>{{ 'Home'|trans }}</span></a></li>
    <li><a href="{{ path('_orders') }}"><i class="fa fa-list-alt navicon"></i> <span>{{ 'Orders'|trans }}</span></a></li>
    <li><a href="#paynaments"><i class="fa fa-cart-plus navicon"></i> <span>{{ 'Payments'|trans }}</span></a></li>
    <li><a href="#feedbacks"><i class="fa fa-envelope navicon"></i> <span>{{ 'Feedbacks'|trans }}</span></a></li>
    <li><a href="#tasks"><i class="fa fa-cog navicon"></i> <span>{{ 'Tasks'|trans }}</span></a></li>
    <li><a href="#stats"><i class="fa fa-line-chart navicon"></i> <span>{{ 'Statistics'|trans }}</span></a></li>
    
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-circle-o navicon"></i> <span>{{ 'Code lists'|trans }}</span> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="{{ path('_job_types') }}"><i class="fa fa-circle-o"></i> {{ 'Job types'|trans }}</a></li>
        </ul>
    </li>
    
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-circle-o navicon"></i> <span>{{ 'Help'|trans }}</span> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="#"><i class="fa fa-question-circle"></i> <span>{{ 'About'|trans }}</span></a></li>
            <li><a href="#"><i class="fa fa-envelope-o"></i> <span>{{ 'Contact'|trans }}</span></a></li>
        </ul>
    </li>
    
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-globe navicon"></i> <span>{{ app.request.locale|upper }}</span> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            {% if app.request.locale != 'en' %}<li><a href="{{ path('_language_change', {'lang':'en'}) }}">EN</a></li>{% endif %}
            {% if app.request.locale != 'hr' %}<li><a href="{{ path('_language_change', {'lang':'hr'}) }}">HR</a></li>{% endif %}
        </ul>
    </li>
</ul>

src/BigPandaDev/MainBundle/Resources/views/Navs/main_nav_public.html.twig
<ul class="nav navbar-nav navbar-left">
    <li><a href="#"><i class="fa fa-question-circle navicon"></i> <span>{{ 'About'|trans }}</span></a></li>
    <li><a href="#"><i class="fa fa-envelope-o navicon"></i> <span>{{ 'Contact'|trans }}</span></a></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-globe navicon"></i> <span>{{ app.request.locale|upper }}</span> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            {% if app.request.locale != 'en' %}<li><a href="{{ path('_language_change', {'lang':'en'}) }}">EN</a></li>{% endif %}
            {% if app.request.locale != 'hr' %}<li><a href="{{ path('_language_change', {'lang':'hr'}) }}">HR</a></li>{% endif %}
        </ul>
    </li>
</ul>